Travel App Python3 SG 2.7.3
Fixed and working off intiial deploynment, N.B. dns still not displayed on output.

diff --git a/couchbase_inc/rightscripts/Couchbase_Server_-_App_and_workload b/couchbase_inc/rightscripts/Couchbase_Server_-_App_and_workload
--- a/couchbase_inc/rightscripts/Couchbase_Server_-_App_and_workload
+++ b/couchbase_inc/rightscripts/Couchbase_Server_-_App_and_workload
@@ -161,8 +161,6 @@ pip install typing
 
 if  [[ "$CB_TRAVEL_DEMO" == "TRUE" ]]; then  
 
-yum -y -q install python3-pip
-
   x=''
   #while [[ "$x" != '[]' ]]; do
     echo "Creating travel-sample bucket"
@@ -191,9 +189,32 @@ yum -y -q install python3-pip
   echo "Running Travel application:"
   cd /root
   
+  #Remove python and pip
+  packages="python-pip python-devel"
+  echo "Removing yum packages: $packages"
+  if ! yum  -y --skip-broken remove $packages; then
+    if ! yum  -y --skip-broken remove $packages; then
+      echo "Could not remove packages";
+      exit 1;
+    fi
+  fi
+  
+  #Install python3 and pip3
+  packages="python3-pip python3-devel cmake3 gcc gcc-c++"
+  echo "Installing yum packages: $packages"
+  if ! yum  -y --skip-broken install $packages; then
+    if ! yum  -y --skip-broken install $packages; then
+      echo "Could not install packages";
+      exit 1;
+    fi
+  fi
+  
+  pip3 install --upgrade pip
+  
   git clone https://github.com/couchbaselabs/try-cb-python.git
   cd try-cb-python
   git checkout mobile-travel-sample-tutorial
+  
   pip3 install -r requirements.txt
   
   #cat travel.py | \
